name: Prelude

on:
  push:
    branches: [ master ]
    paths: "prelude/server/**"
  pull_request:
    branches: [ master ]
    paths: "prelude/server/**"

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Dependencies
        run: |
          cd prelude/server
          npm i --production
      - name: Build App
        run: npm run build
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Dependencies
        run: |
          cd prelude/server
          npm i --production
      - name: Test App
        run: npm test
          
