name: Prelude

on:
  push:
    branches: [ master ]
    paths: "prelude/server/**"
  pull_request:
    branches: [ master ]
    paths: "prelude/server/**"

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      working-directory: ./prelude/server
    steps:
      - uses: actions/checkout@v2
      - name: Install Dependencies
        run: npm i --production
        working-directory: ${{ env.working-directory }}
      - name: Build App
        run: npm run build
        working-directory: ${{ env.working-directory }}
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Dependencies
        run: npm i --production
        working-directory: ${{ env.working-directory }}
      - name: Test App
        run: npm test
        working-directory: ${{ env.working-directory }}
          
